baseURL = 'https://moldinspecton247.com/'
languageCode = 'en-us'
title = "Mold Inspection 24/7"
pagination.pageSize = 20
pagination.path = "/"
summaryLength = 10

[taxonomies]
# category = "categories"

[permalinks]
  posts = ":section/:year/:month/:day/:title/"

  [permalinks.section]
    services = "/:slug/"

[markup.goldmark.renderer]
unsafe = true

[module]
replacements = "local/component-library -> ../component-library"

[[module.imports]]
path = 'local/component-library'

[[module.imports]]
path = 'github.com/cloudcannon/bookshop/hugo/v3'