[build]
  command = "hugo && npx -y pagefind --site public"
  publish = "public"

[build.environment]
  HUGO_VERSION = "v0.147.9"


[[redirects]]
  from = "/home/"
  to = "/"
  status = 301
  force = false
[[redirects]]
  from = "/contact-location/"
  to = "/contact/"
  status = 301
  force = false
[[redirects]]
  from = "/preventing-mold/"
  to = "/services/"
  status = 301
  force = false
[[redirects]]
  from = "/removing-mold/"
  to = "/services/"
  status = 301
  force = false
[[redirects]]
  from = "/mold-testing/"
  to = "/services/"
  status = 301
  force = false
[[redirects]]
  from = "/how-it-works/"
  to = "/"
  status = 301
  force = false
[[redirects]]
  from = "/commercial-mold-services/"
  to = "/services/"
  status = 301
  force = false
[[redirects]]
  from = "/more-than-mold/"
  to = "/"
  status = 301
  force = false
[[redirects]]
  from = "/mold-iaq-assessor/"
  to = "/services/"
  status = 301
  force = false
[[redirects]]
  from = "/faulty-spray-foam-insulation/"
  to = "/"
  status = 301
  force = false
[[redirects]]
  from = "/whats-more-important-than-breathing/"
  to = "/"
  status = 301
[[redirects]]
  from = "/videofatal-fungus-fungus-is-mold/"
  to = "/"
  status = 301
[[redirects]]
  from = "/residential-commercial-indoor-air-quality-test/"
  to = "/"
  status = 301
[[redirects]]
  from = "/beyond-mold-dust-characterization-bacterial-vocs-dna-pcr-much-more/"
  to = "/"
  status = 301
[[redirects]]
  from ="/church-iaq/"
  to = "/services/"
  status = 301
