backend:
  name: github
  repo: Kgelibrizzi/Moldinspection247.com # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  base_url: https://moldinspection247.com/
  auth_endpoint: /.netlify/functions/auth
media_folder: "static/images/" # Folder where user uploaded files should go
public_folder: "/images/"

editor:
  preview: false


collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/_index.md"
        fields:
          - { name: title, label: Meta Title(SEO), widget: string, required: true }
          - { name: seo, label: SEO, widget: object, fields: [
              { name: page_description, label: Meta Description(SEO), widget: text, required: true },
              { name: canonical_url, label: Canonical URL, widget: string, required: false },
              { name: featured_image, label: Featured Image, widget: image, required: false },
              { name: author_twitter_handle, label: Author Twitter Handle, widget: string, required: false },
            ]}
          - { name: big_hero, label: Big Hero Section, widget: object, fields: [
              { name: heading, label: Heading (Big Text), widget: string },
              { name: preheading, label: Text, widget: string },
              { name: background_image, label: Background Image, widget: image, required: false },
              { name: link, label: Primary Link, widget: object, fields: [
                { name: text, label: Link Text, widget: string },
                { name: url, label: Link URL, widget: string }
              ]},
              { name: link_2, label: Secondary Link, widget: object, fields: [
                { name: text ,label: Link Text, widget: string },                 
                { name: url ,label: Link URL, widget: string }
              ]}
            ]}
          - { name: services, label: Services Section, widget: object, fields: [
              { name: preheading, label: Preheading(Small Text), widget: string },
              { name: heading, label: Heading (Big Text), widget: string },
              { name: content, label: Content, widget: text },
              { name: sections, label: Services List, widget: list, fields: [
                { name: title, label: Service Title, widget: string },
                { name: icon_path, label: Service Icon, widget: image },
                { name: content, label: Service Description, widget: string },
                { name: url, label: Service Page Link, widget: string }
              ]}
            ]}
          - { name: certification, label: Certifications Section, widget: object, fields: [
              { name: preheading, label: Preheading(Small Text), widget: string },
              { name: heading, label: Heading (Big Text), widget: string },
              { name: credentials, label: Bullet Point Credentials, widget: list, fields: [
                { name: heading, label: Credentials, widget: string },
              ]},
              { name: sections, label: Certifications List, widget: list, fields: [
                { name: image_path, label: certification/ partner badge, widget: image },
                { name: image_alt, label: Image Alternative Text, widget: string },
              ]}
            ]}
          - { name: counter, label: Industries Section, widget: object, fields: [
              { name: heading, label: Heading (Big Text), widget: string },
              { name: numbers, label: Industries List, widget: list, fields: [
                { name: icon_path, label: Icon, widget: image },
                { name: number, label: Number, widget: number },
                { name: suffix, label: Suffix, widget: string },
                { name: text, label: Industry, widget: string },
              ]}
            ]}
          - { name: about, label: About Section, widget: object, fields: [
              { name: preheading, label: Preheading(Small Text), widget: string },  
              { name: heading, label: Heading (Big Text), widget: string, required: true },  
              { name: content, label: content, widget: text },
              { name: background_image, label: About Photo, widget: image, required: false },
              { name: link, label: About Button, widget: object, fields: [
                { name: text, label: Link Text, widget: string },                   
                { name: url, label: Link URL, widget: string } 
              ]}
            ]}
          - { name: cta, label: CTA Section, widget: object, fields: [
              { name: preheading, label: Preheading(Small Text), widget: string },
              { name: heading, label: Heading (Big Text), widget: string },
              { name: content, label: content, widget: string },
              { name: phone, label: Phone, widget: string },
            ]}
      - name: "services"
        label: "Services Page"
        file: "content/services.md"
        fields:
          - { name: title, label: Meta Title(SEO), widget: string, required: true }
          - { name: seo, label: SEO, widget: object, fields: [
              { name: page_description, label: Meta Description(SEO), widget: text, required: true },
              { name: canonical_url, label: Canonical URL, widget: string, required: false },
              { name: featured_image, label: Featured Image, widget: image, required: false },
              { name: author_twitter_handle, label: Author Twitter Handle, widget: string, required: false },
            ]}
          - { name: hero, label: Hero Section, widget: object, fields: [
              { name: title, label: Heading H1 (Big Text), widget: string },
              { name: preheading, label: Text, widget: string },
              { name: background_image, label: Background Image, widget: image, required: false },
            ]}
          - { name: services, label: Services Section, widget: object, fields: [
              { name: preheading, label: Preheading(Small Text), widget: string },
              { name: heading, label: Heading (Big Text), widget: string },
              { name: content, label: Content, widget: text },
              { name: sections, label: Services List, widget: list, fields: [
                { name: title, label: Service Title, widget: string },
                { name: icon_path, label: Service Icon, widget: image },
                { name: content, label: Service Description, widget: string },
                { name: url, label: Service Page Link, widget: string }
              ]}
            ]}
          - { name: cta, label: CTA, widget: object, fields: [
            { name: preheading, label: Preheading(Small Text), widget: string },
            { name: heading, label: Heading(Big Text), widget: string, required: true },
            { name: background_image, label: Background Image, widget: image, required: false },
            { name: button, label: Button, widget: object, fields: [
              { name: text, label: Link Text, widget: string },                    
              { name: url, label: Link URL, widget: string }
            ]},
            { name: button_2, label: Button, widget: object, fields: [
              { name: text, label: Link Text, widget: string },                    
              { name: url, label: Link URL, widget: string }
            ]},
          ]}
      - name: "why_choose_us"
        label: "Why Choose Us Page"
        file: "content/why-choose-us.md"
        fields:
          - { name: title, label: Meta Title(SEO), widget: string, required: true }
          - { name: seo, label: SEO, widget: object, fields: [
              { name: page_description, label: Meta Description(SEO), widget: text, required: true },
              { name: canonical_url, label: Canonical URL, widget: string, required: false },
              { name: featured_image, label: Featured Image, widget: image, required: false },
              { name: author_twitter_handle, label: Author Twitter Handle, widget: string, required: false },
            ]}
          - { name: hero, label: Hero Section, widget: object, fields: [
              { name: title, label: Heading H1 (Big Text), widget: string },
              { name: preheading, label: Text, widget: string },
              { name: background_image, label: Background Image, widget: image, required: false },
            ]}
          - { name: certification, label: Certifications Section, widget: object, fields: [
              { name: content, label: Content, widget: text },
              { name: heading, label: Heading (Big Text), widget: string },
              { name: credentials, label: Bullet Point Credentials, widget: list, fields: [
                { name: heading, label: Credentials, widget: string },
              ]},
              { name: sections, label: Certifications List, widget: list, fields: [
                { name: image_path, label: certification/ partner badge, widget: image },
                { name: image_alt, label: Image Alternative Text, widget: string },
              ]}
            ]}
          - { name: counter, label: Industries Section, widget: object, fields: [
              { name: heading, label: Heading (Big Text), widget: string },
              { name: content, label: Content, widget: text },
              { name: numbers, label: Industries List, widget: list, fields: [
                { name: icon_path, label: Icon, widget: image },
                { name: number, label: Number, widget: number },
                { name: suffix, label: Suffix, widget: string },
                { name: text, label: Industry, widget: string },
              ]}
            ]}
          - { name: cta, label: CTA Section, widget: object, fields: [
              { name: preheading, label: Preheading(Small Text), widget: string },
              { name: heading, label: Heading (Big Text), widget: string },
              { name: content, label: content, widget: string },
              { name: phone, label: Phone, widget: string },
            ]}
      - name: "about"
        label: "About Page"
        file: "content/about.md"
        fields:
          - { name: title, label: Meta Title(SEO), widget: string, required: true }
          - { name: url, label: Page URL, widget: string, required: true }
          - { name: layout, label: Layout, widget: select, options: ["about"], required: true }
          - { name: seo, label: SEO, widget: object, fields: [
              { name: page_description, label: Meta Description(SEO), widget: string, required: true },
              { name: canonical_url, label: Canonical URL, widget: string, required: false },
              { name: featured_image, label: Featured Image, widget: image, required: false },
              { name: author_twitter_handle, label: Author Twitter Handle, widget: string, required: false },
            ]}
          - { name: hero, label: Hero Section, widget: object, fields: [
              { name: title, label: Heading H1 (Big Text), widget: string },
              { name: preheading, label: Text, widget: string },
              { name: background_image, label: Background Image, widget: image, required: false },
            ]}
          - { name: start, label: About Section, widget: object, fields: [
              { name: preheading, label: Preheading(Small Text), widget: string },  
              { name: heading, label: Heading (Big Text), widget: string, required: true },  
              { name: content, label: content, widget: text },
              { name: image_path, label: About Photo, widget: image, required: false },
              { name: image_alt, label: Image alt text, widget: string },
              { name: button, label: About Button, widget: object, fields: [
                { name: text, label: Link Text, widget: string },                   
                { name: url, label: Link URL, widget: string } 
              ]}
            ]}

      - name: "contact"
        label: "Contact Us Page"
        file: "content/contact.md"
        fields:
          - { name: title, label: Meta Title(SEO), widget: string, required: true }
          - { name: layout, label: Layout, widget: select, options: ["contact"], required: true }
          - { name: url, label: Page URL, widget: string, required: true }
          - { name: seo, label: SEO, widget: object, fields: [
              { name: page_description, label: Meta Description(SEO), widget: string, required: true },
              { name: canonical_url, label: Canonical URL, widget: string, required: false },
              { name: featured_image, label: Featured Image, widget: image, required: false },
              { name: author_twitter_handle, label: Author Twitter Handle, widget: string, required: false },
            ]}
          - { name: hero, label: Hero Section, widget: object, fields: [
              { name: title, label: Heading H1 (Big Text), widget: string, required: true },
              { name: preheading, label: Text, widget: string },
              { name: background_image, label: Background Image, widget: image, required: false },
            ]}
          - { name: contact_form, label: Contact Section, widget: object, fields: [
              { name: preheading, label: Preheading(Small Text), widget: string },
              { name: heading, label: Heading (Big Text), widget: string },
              { name: form_heading, label: Form Heading, widget: string },
              { name: phone, label: phone 1, widget: string },
              { name: email, label: Email Address, widget: string },
              { name: button, label: About Button, widget: object, fields: [
                { name: text, label: Link Text, widget: string },                   
                { name: url, label: Link URL, widget: string }, 
                { name: open_in_new_tab, label: Open in new tab, widget: boolean, default: true },
              ]},
              { name: qrcode, label: QR Code, widget: object, fields: [
                { name: image_path, label: Image, widget: image, required: false },
                { name: placeholder, label: Placeholder text, widget: string }, 
                { name: text, label: Text above QR Code, widget: string }, 
              ]},
              { name: contact_form_enabled, label: Enable Contact Form, widget: boolean, default: false,
               hint: "Toggle to enable/ disable it. Once enabled here, remember to also enable forms on Netlify so that you can start receiving contact form submissions. Contact form responses can only be viewed on the Netlify.com dashboard."
              }
            ]}
      - name: "404"
        label: "404 Page"
        file: "content/404.md"
        fields:
          - { name: title, label: Meta Title(SEO), widget: string, required: true }
          - { name: url, label: Page URL, widget: string, required: true }
          - { name: hero, label: Hero Section, widget: object, fields: [
              { name: title, label: Heading H1 (Big Text), widget: string, required: true },
              { name: preheading, label: Text, widget: string },
              { name: background_image, label: Background Image, widget: image, required: false },
            ]}
          - { name: body, label: Page Content, widget: markdown, required: true }
          - { name: sitemap, label: Sitemap , widget: object, fields: [
              { name: disable, label: Disable, widget: boolean, required: true, default: true }
            ]}
  - name: "settings"
    label: "Site Settings"
    files:
      - name: "company"
        label: "Company Details"
        file: "data/company.yml"
        fields:
          - { name: BaseURL, label: Full Website Address, widget: string, hint: "Use the full website address. Example: https://geriskmanagement.com" }
          - { name: SEO_options, label: SEO Options, widget: object, fields: [
              { name: site_title, label: Site Title, widget: string },
              { name: description, label: Meta Description, widget: string }
            ]}
          - { name: open_graph_type, label: Open Graph Type , widget: select, options: ["website"]}
          - { name: twitter_handle, label: Twitter Handle, widget: string, required: false }
          - { name: social_media_share_image, label: Website Icon(.png), widget: image, required: false }
          - { name: google_analytics_key, label: Google Analytics Key, widget: string, required: false }
          - { name: favicon, label: Favicon, widget: image }
          - { name: logo_dark, label: Logo for Dark Background, widget: image }
          - { name: logo_light, label: Logo for Light Background, widget: image }
          - { name: facebook, label: Facebook , widget: string, required: false }
          - { name: twitter, label: Twitter, widget: string, required: false }
          - { name: github, label: GitHub, widget: string, required: false }
          - { name: pinterest, label: Pinterest, widget: string, required: false }
          - { name: support, label: Contact Details, widget: object, fields: [      
              { name: phone, label: phone, widget:  string },
              { name: email, label: Email Address, widget: string },
              { name: button, label: Payment Button, widget: object, fields: [
                { name: text, label: Link Text, widget: string },                   
                { name: url, label: Link URL, widget: string }, 
                { name: open_in_new_tab, label: Open in new tab, widget: boolean, default: true },
              ]},
            ]}
          - { name: copyright_html, label: Copyright Footer Text, widget: string }
          - { name: backlink, label: Backlink Text, widget: string }
          - { name: default_hero_bg_image, label: Default Hero Background Image, widget: image }
          - { name: about_footer_title, label: About Us Footer Title, widget: string }
          - { name: about_footer_content, label: About Us Footer Content, widget: text }
      - name: "nav"
        label: "Navbar Links"
        file: "data/nav.yml"
        fields:
          - { name: menu_items, label: Nav Links List , widget: list, label_singular: Nav Link, fields: [
              { name: name, label: Link Text, widget: string },
              { name: url, label: Link URL, widget: string },
              { name: "_id", label: ID, widget: select, options: ["link"]  },
              {  name: open_in_new_tab, label: Link Opens in a New Tab, widget: boolean, default: false }
            ]}
      - name: "footer"
        label: "Footer Details"
        file: "data/footer.yml"
        fields:
          - { name: column, label: Column , widget: list,  fields: [
              { name: heading, label: Heading (Big Text), widget: string },
              { name: items, label: Links List, widget: list, fields: [ 
                { name: name, label: Link text, widget: string },
                { name: url, label: Link URL, widget: string },
                { name: open_in_new_tab, label: Link Opens in a New Tab, widget: boolean, default: false }
              ]}
            ]}
      - name: "cta_mini"
        label: "Mini CTA"
        file: "data/cta_mini.yml"
        fields:
          - { name: enabled, label: Enabled on Mini CTA on All Services Pages, widget: boolean }
          - { name: preheading, label: Preheading(Small Text), widget: string }
          - { name: heading, label: Heading (Big Text), widget: string }
          - { name: background_image, label: Background Image, widget: image }
          - { name: button, label: Button Link, widget: object, fields: [
              { name: url, label: Link URL, widget: string },
              { name: text, label: Link Text, widget: string }
            ]}
            