# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: certification
  description: certification section
  icon: build
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  preheading: ""
  heading: ""
  sections:
    - image_path: ""
      image_alt: ""

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:
  preheading: Our certifications
  heading: "We provide a wide range of creative services "
  sections:
    - image_path: /example-image.png
      image_alt: certification

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: {}
